/**
 * What a demo profile should look like, per trade.
 *
 * `queries` are what gets sent to the stock-photo provider. They are written
 * as the WORK, not the job title: "plumber" returns men posing with a wrench,
 * "leaking pipe under sink repair" returns the thing a customer is actually
 * trying to recognise on a portfolio grid. That distinction is the whole point
 * of this file — a marketplace where every plumber shows the same stock
 * headshot argues for nobody.
 *
 * `captions` are the lightbox text. Kept concrete and Jamaican in register, so
 * the grid reads as somebody's real job history rather than a gallery.
 */
export const TRADE_IMAGERY = {
  plumbing: {
    queries: [
      'plumber repairing pipe under sink',
      'leaking water pipe repair',
      'bathroom sink plumbing installation',
      'water heater installation plumber',
      'new bathroom fixtures installed',
      'copper pipe fitting work',
    ],
    captions: [
      'Under-sink leak traced and replaced',
      'Burst pipe repaired, same day',
      'New bathroom suite plumbed in',
      'Solar water heater installed',
      'Kitchen tap and drain replaced',
      'Full pipe run for a new build',
    ],
  },
  electrical: {
    queries: [
      'electrician wiring breaker panel',
      'electrical outlet installation',
      'ceiling light fixture installation',
      'house rewiring electrical work',
      'solar panel installation roof',
      'electrical junction box wiring',
    ],
    captions: [
      'Breaker panel upgraded and labelled',
      'Full house rewire completed',
      'New sockets run to the back room',
      'Ceiling fixtures fitted throughout',
      'Solar array wired and tied in',
      'Fault traced and fixed in an evening',
    ],
  },
  carpentry: {
    queries: [
      'carpenter building custom cabinet',
      'handmade wooden furniture workshop',
      'fitted kitchen cabinets woodwork',
      'wooden door frame installation',
      'custom built wardrobe interior',
      'carpentry workshop hand tools wood',
    ],
    captions: [
      'Custom kitchen cabinets, mahogany',
      'Built-in wardrobe, fitted to the wall',
      'Hardwood door hung and finished',
      'Bedframe built to measurement',
      'Shelving unit for a shop counter',
      'Window frames replaced in cedar',
    ],
  },
  painting: {
    queries: [
      'painter painting interior wall roller',
      'freshly painted living room interior',
      'house exterior painting work',
      'decorative wall finish painting',
      'painter on ladder painting building',
      'painted feature wall interior design',
    ],
    captions: [
      'Living room repainted, two coats',
      'Shopfront exterior, weather-sealed',
      'Feature wall in a bedroom',
      'Whole-house interior refresh',
      'Gates and grills stripped and painted',
      'Skim coat and finish on new plaster',
    ],
  },
  masonry: {
    queries: [
      'mason laying concrete blocks wall',
      'stone retaining wall construction',
      'concrete steps construction',
      'bricklayer building wall mortar',
      'decorative stonework exterior',
      'house foundation concrete work',
    ],
    captions: [
      'Block wall raised and plastered',
      'Retaining wall, dry-stacked stone',
      'Concrete steps and landing poured',
      'Foundation laid for an extension',
      'Decorative stone facing on a porch',
      'Boundary wall, 40 feet',
    ],
  },
  tiling: {
    queries: [
      'tiler laying floor tiles',
      'bathroom wall tiling work',
      'kitchen backsplash tile installation',
      'porcelain floor tiles installed',
      'mosaic tile work bathroom',
      'tile cutting installation tools',
    ],
    captions: [
      'Bathroom floor and walls, porcelain',
      'Kitchen backsplash in mosaic',
      'Veranda tiled in natural stone',
      'Living room floor, large format',
      'Shower recess fully retiled',
      'Regrouted and sealed throughout',
    ],
  },
  welding: {
    queries: [
      'welder welding metal gate',
      'wrought iron gate fabrication',
      'metal stair railing welding',
      'window burglar bars metal work',
      'welding sparks workshop fabrication',
      'custom metal fabrication workshop',
    ],
    captions: [
      'Driveway gate, custom fabricated',
      'Window grills fitted and painted',
      'Stair rail in wrought iron',
      'Balcony railing, powder-coated',
      'Trailer frame repaired',
      'Security grill for a shop front',
    ],
  },
  mechanics: {
    queries: [
      'mechanic repairing car engine',
      'car brake pad replacement garage',
      'auto repair shop car lift',
      'engine diagnostic computer car',
      'car suspension repair workshop',
      'mechanic changing car oil',
    ],
    captions: [
      'Full service and oil change',
      'Brake pads and discs replaced',
      'Suspension rebuilt front and rear',
      'Engine diagnostics run and cleared',
      'Timing belt done at 90k',
      'Pre-purchase inspection completed',
    ],
  },
  'appliance-repair': {
    queries: [
      'repairing washing machine technician',
      'appliance repair technician kitchen',
      'refrigerator repair technician',
      'oven stove repair technician',
      'washing machine parts repair',
      'home appliance service tools',
    ],
    captions: [
      'Washer drum bearing replaced',
      'Dryer element and thermostat fixed',
      'Stove igniters replaced, all four',
      'Fridge compressor diagnosed',
      'Microwave door switch repaired',
      'Washing machine pump unblocked',
    ],
  },
  landscaping: {
    queries: [
      'landscaper mowing lawn garden',
      'tropical garden landscaping design',
      'hedge trimming garden maintenance',
      'garden bed planting landscaping',
      'tree trimming service worker',
      'manicured lawn tropical yard',
    ],
    captions: [
      'Lawn cut and edged, weekly plan',
      'Hedge shaped and cleared back',
      'Garden beds replanted',
      'Overgrown yard cleared',
      'Mango tree pruned safely',
      'Irrigation laid for a new lawn',
    ],
  },
  'ac-refrigeration': {
    queries: [
      'air conditioner installation technician',
      'hvac technician servicing ac unit',
      'split unit air conditioner wall',
      'refrigeration cold room equipment',
      'ac unit cleaning maintenance',
      'air conditioning repair tools gauges',
    ],
    captions: [
      'Split unit installed and charged',
      'AC serviced, coils cleaned',
      'Cold room thermostat replaced',
      'Gas topped up, leak sealed',
      'Two units fitted in one afternoon',
      'Freezer unit back to temperature',
    ],
  },
  roofing: {
    queries: [
      'roofer installing roof shingles',
      'metal roof installation work',
      'roof repair worker on roof',
      'new roof construction house',
      'roof gutter installation',
      'zinc roof sheet installation',
    ],
    captions: [
      'Zinc sheets replaced after storm',
      'Full roof reframed and covered',
      'Gutters fitted and fall-tested',
      'Ridge capping sealed',
      'Leak traced and patched',
      'Shingle roof laid on a new build',
    ],
  },
  tutoring: {
    queries: [
      'tutor teaching student at table',
      'student studying with teacher homework',
      'private tutoring lesson child',
      'maths tutoring notebook study',
      'teacher helping student classroom',
      'study session books notes',
    ],
    captions: [
      'Weekly maths sessions, grade 9',
      'Homework support after school',
      'Reading confidence in eight weeks',
      'One-to-one, at the kitchen table',
      'Small group revision class',
      'Parent progress report every month',
    ],
  },
  'exam-prep': {
    queries: [
      'student exam preparation studying',
      'past paper revision notes study',
      'teacher explaining exam question',
      'classroom exam revision session',
      'student writing exam desk',
      'study notes highlighter revision',
    ],
    captions: [
      'CSEC maths, past papers drilled',
      'CAPE biology revision block',
      'SBA structured and submitted',
      'Mock exam marked and reviewed',
      'Grade 1 in English, first sitting',
      'Six-week intensive before exams',
    ],
  },
  'music-lessons': {
    queries: [
      'piano lesson teacher student',
      'guitar lesson teaching music',
      'child learning keyboard music',
      'music teacher with student instrument',
      'singing voice lesson studio',
      'sheet music practice instrument',
    ],
    captions: [
      'Piano from scratch, adult beginner',
      'Guitar chords in six lessons',
      'Voice coaching for a church solo',
      'Keyboard lessons, after school',
      'First recital, eight years old',
      'Theory and practice together',
    ],
  },
  'driving-lessons': {
    queries: [
      'driving instructor teaching student car',
      'learner driver behind wheel',
      'driving lesson car steering wheel',
      'driving school car road',
      'parallel parking practice driving',
      'road test preparation driving',
    ],
    captions: [
      'Passed first try, road test',
      'Parallel parking, finally clicked',
      'Highway confidence in four lessons',
      'Nervous driver, patient pace',
      'Manual gearbox from scratch',
      'Provisional to full licence',
    ],
  },
  hairdressing: {
    queries: [
      'hair braiding salon stylist',
      'box braids hairstyle black woman',
      'natural hair styling salon',
      'cornrow braids hairstyle',
      'hair salon stylist working client',
      'protective hairstyle twist out',
    ],
    captions: [
      'Knotless box braids, mid-back',
      'Cornrows with a fresh part',
      'Silk press on natural hair',
      'Twist-out, defined and soft',
      'Wig install, glueless',
      'Colour and trim, same sitting',
    ],
  },
  barbering: {
    queries: [
      'barber cutting hair barbershop',
      'fade haircut barber clippers',
      'barbershop client haircut mirror',
      'beard trim barber shop',
      'mens haircut styling barber',
      'barber tools clippers shop',
    ],
    captions: [
      'Skin fade with a line-up',
      'Beard shaped and hot-towelled',
      'Taper fade, school-ready',
      'Full cut and shave',
      'Wedding-day line-up',
      'Kids cuts, Saturday morning',
    ],
  },
  'nail-tech': {
    queries: [
      'manicure nail technician salon',
      'gel nail art design hands',
      'pedicure salon foot treatment',
      'acrylic nails design closeup',
      'nail salon technician working',
      'painted nails colourful design',
    ],
    captions: [
      'Gel set with hand-painted art',
      'Acrylic full set, almond',
      'Pedicure and callus treatment',
      'French tips for a wedding party',
      'Chrome finish, two weeks strong',
      'Fill-in and reshape',
    ],
  },
  makeup: {
    queries: [
      'makeup artist applying makeup client',
      'bridal makeup application',
      'makeup brushes palette cosmetics',
      'professional makeup studio work',
      'glam makeup look portrait',
      'makeup artist backstage work',
    ],
    captions: [
      'Bridal glam, lasted the whole day',
      'Soft beat for a graduation',
      'Full face for a photoshoot',
      'Bridesmaids, all five',
      'Evening look, bold lip',
      'Natural finish for a christening',
    ],
  },
  massage: {
    queries: [
      'massage therapist treatment table',
      'back massage therapy spa',
      'spa massage room relaxing',
      'deep tissue massage therapy',
      'massage oils spa treatment',
      'therapist hands massage shoulder',
    ],
    captions: [
      'Deep tissue for lower back pain',
      'Sports recovery session',
      'Prenatal massage, side-lying',
      'Hot stone, full hour',
      'Neck and shoulder, desk workers',
      'Home visit with own table',
    ],
  },
  fitness: {
    queries: [
      'personal trainer coaching client gym',
      'outdoor fitness training session',
      'gym workout weights training',
      'fitness bootcamp group exercise',
      'trainer with client exercise',
      'home workout training session',
    ],
    captions: [
      'Twelve-week transformation',
      'Morning bootcamp, six a.m.',
      'Strength programme, three days',
      'Post-injury return to training',
      'Home sessions, no equipment',
      'Group class at the park',
    ],
  },
  catering: {
    queries: [
      'caribbean food catering buffet',
      'chef cooking large pot kitchen',
      'catered event food display',
      'jerk chicken grill caribbean food',
      'caterer plating food event',
      'buffet table food spread party',
    ],
    captions: [
      'Curry goat and rice for 80',
      'Jerk pan set up on site',
      'Wedding buffet, three mains',
      'Office lunch, weekly order',
      'Sunday dinner, delivered hot',
      'Christmas function, 150 covers',
    ],
  },
  baking: {
    queries: [
      'decorated birthday cake bakery',
      'baker decorating cake icing',
      'wedding cake tiers decoration',
      'fresh baked pastries display',
      'cupcakes decorated bakery',
      'homemade bread baking kitchen',
    ],
    captions: [
      'Two-tier birthday cake, buttercream',
      'Wedding cake, three tiers',
      'Black cake for Christmas',
      'Cupcake tower for a christening',
      'Hardo bread, fresh daily',
      'Custom number cake, sweet 16',
    ],
  },
  bartending: {
    queries: [
      'bartender making cocktail bar',
      'cocktails drinks bar service',
      'mobile bar setup event',
      'bartender pouring drink party',
      'cocktail garnish preparation',
      'bar counter drinks event',
    ],
    captions: [
      'Mobile bar for a beach wedding',
      'Rum punch station, all night',
      'Cocktail menu built for the event',
      'Corporate function, 200 guests',
      'Two bartenders, one long night',
      'Signature drink for the couple',
    ],
  },
  'event-planning': {
    queries: [
      'event decoration wedding venue',
      'party decoration balloons setup',
      'wedding reception table setting',
      'event planner coordinating venue',
      'outdoor event setup chairs',
      'birthday party decoration setup',
    ],
    captions: [
      'Reception styled end to end',
      'Balloon arch and backdrop',
      'Table settings for 120',
      'Outdoor ceremony, full setup',
      'Corporate launch, run of show',
      'Baby shower, themed throughout',
    ],
  },
  'dj-music': {
    queries: [
      'dj mixing music turntables party',
      'dj sound system speakers event',
      'dj booth lights party crowd',
      'sound system setup stage event',
      'dj equipment mixer headphones',
      'party crowd dancing music event',
    ],
    captions: [
      'Sound and lights for a wedding',
      'Full rig, outdoor session',
      'Reception set, kept it full',
      'Corporate event, clean sound',
      'Birthday party, all night',
      'Two-deck setup with mics',
    ],
  },
  photography: {
    queries: [
      'photographer with camera shooting',
      'wedding photography couple portrait',
      'photography studio lighting setup',
      'graduation portrait photography',
      'event photographer working camera',
      'portrait photography session outdoor',
    ],
    captions: [
      'Wedding, full day coverage',
      'Graduation portraits on campus',
      'Family shoot at the beach',
      'Studio headshots for a business',
      'Christening, church and reception',
      'Product shots for an online shop',
    ],
  },
  cleaning: {
    queries: [
      'cleaner cleaning house professional',
      'deep cleaning kitchen service',
      'housekeeping cleaning supplies',
      'office cleaning professional service',
      'bathroom deep clean scrubbing',
      'tidy clean living room after cleaning',
    ],
    captions: [
      'Move-out deep clean, three bed',
      'Weekly housekeeping',
      'Post-construction cleanup',
      'Office, after hours',
      'Kitchen degreased top to bottom',
      'Bathrooms scrubbed and sealed',
    ],
  },
  laundry: {
    queries: [
      'laundry service folded clothes',
      'ironing clothes laundry service',
      'washing machine laundry basket',
      'folded linen stack laundry',
      'laundry shop washing service',
      'ironed shirts hanging rail',
    ],
    captions: [
      'Wash, dry and fold, next day',
      'Uniforms pressed weekly',
      'Curtains and bedding done',
      'Pickup and delivery included',
      'Shirts ironed and hung',
      'Bulk load for a guest house',
    ],
  },
  childcare: {
    queries: [
      'nanny playing with child',
      'children playing daycare toys',
      'child homework help adult',
      'babysitter reading to child',
      'kids activities craft table',
      'toddler playing safe indoors',
    ],
    captions: [
      'After-school care, two children',
      'School run and homework',
      'Full-day care during holidays',
      'Reading time every afternoon',
      'Meal prep and nap routine',
      'Craft afternoons, rain or shine',
    ],
  },
  'elder-care': {
    queries: [
      'caregiver helping elderly person',
      'nurse assisting senior at home',
      'elderly care companionship home',
      'caregiver elderly hands support',
      'senior care home visit',
      'elderly person with carer walking',
    ],
    captions: [
      'Daily visits, medication reminders',
      'Companionship and light meals',
      'Post-hospital recovery support',
      'Live-in care, weekdays',
      'Mobility support and exercises',
      'Family kept updated each week',
    ],
  },
  'pest-control': {
    queries: [
      'pest control technician spraying',
      'exterminator treating home pests',
      'pest control equipment spray',
      'termite treatment technician',
      'pest control service uniform',
      'spraying insecticide home service',
    ],
    captions: [
      'Roach treatment, follow-up included',
      'Termite barrier laid',
      'Rodent proofing, whole house',
      'Mosquito fogging for an event',
      'Restaurant contract, monthly',
      'Ant nest traced and cleared',
    ],
  },
  'pool-cleaning': {
    queries: [
      'pool cleaning service technician',
      'swimming pool maintenance net',
      'clean swimming pool blue water',
      'pool chemical testing water',
      'pool pump filter maintenance',
      'pool vacuum cleaning equipment',
    ],
    captions: [
      'Green to clean in three days',
      'Weekly service, villa pool',
      'Filter and pump serviced',
      'Chemicals balanced and logged',
      'Tiles brushed, waterline clear',
      'Hotel pool, daily contract',
    ],
  },
  dressmaking: {
    queries: [
      'seamstress sewing dress machine',
      'tailor measuring fabric suit',
      'dressmaking studio fabric sewing',
      'custom dress design tailoring',
      'sewing machine stitching fabric',
      'tailored suit fitting alterations',
    ],
    captions: [
      'Bridesmaid dresses, set of four',
      'Suit taken in and hemmed',
      'School uniforms, bulk order',
      'Church outfit, custom pattern',
      'Zip replaced, invisible finish',
      'Graduation dress from a sketch',
    ],
  },
  'shoe-repair': {
    queries: [
      'shoe repair cobbler workshop',
      'cobbler fixing leather shoe',
      'shoe resoling repair tools',
      'leather shoe restoration polish',
      'shoemaker workshop leather',
      'repaired leather boots pair',
    ],
    captions: [
      'Resoled and stitched, good as new',
      'Heels rebuilt on court shoes',
      'Leather cleaned and re-dyed',
      'Zip replaced on tall boots',
      'Handbag strap repaired',
      'Work boots given another year',
    ],
  },
  upholstery: {
    queries: [
      'upholstery furniture reupholstering sofa',
      'upholsterer working fabric chair',
      'reupholstered armchair fabric',
      'furniture foam cushion replacement',
      'upholstery workshop fabric tools',
      'car seat upholstery repair',
    ],
    captions: [
      'Three-seater fully reupholstered',
      'Dining chairs, set of six',
      'Foam replaced, sofa sits new',
      'Car seats retrimmed',
      'Headboard built and covered',
      'Cushions recovered in outdoor fabric',
    ],
  },
  'furniture-making': {
    queries: [
      'furniture maker workshop woodworking',
      'handmade wooden table craftsmanship',
      'custom wardrobe furniture build',
      'woodworking bench tools furniture',
      'handcrafted wooden bed frame',
      'artisan furniture workshop wood',
    ],
    captions: [
      'Dining table in local hardwood',
      'Wardrobe built to the alcove',
      'Bedframe, king, solid wood',
      'Shop shelving, made to fit',
      'Outdoor bench, sealed for weather',
      'Desk built for a home office',
    ],
  },
  'computer-repair': {
    queries: [
      'computer technician repairing laptop',
      'laptop repair motherboard tools',
      'computer repair workshop technician',
      'replacing laptop screen repair',
      'desktop computer repair inside',
      'technician fixing computer hardware',
    ],
    captions: [
      'Laptop screen replaced same day',
      'Virus cleared, Windows reinstalled',
      'SSD upgrade, boots in seconds',
      'Data recovered from a dead drive',
      'Keyboard and battery swapped',
      'Office network set up, six machines',
    ],
  },
  'phone-repair': {
    queries: [
      'phone repair technician screen',
      'smartphone screen replacement repair',
      'mobile phone repair tools bench',
      'technician fixing phone motherboard',
      'cracked phone screen repair',
      'phone repair shop workbench',
    ],
    captions: [
      'Cracked screen replaced in 40 mins',
      'Battery swap, holds charge again',
      'Charging port cleaned and reflowed',
      'Water damage recovered',
      'Back glass replaced',
      'Screen protector and case fitted',
    ],
  },
  'web-design': {
    queries: [
      'web designer working laptop design',
      'website design mockup screen',
      'graphic design workspace computer',
      'logo design sketches desk',
      'designer working on branding',
      'web development code screen',
    ],
    captions: [
      'Website for a small restaurant',
      'Logo and business cards',
      'Online menu with ordering',
      'Flyers for a launch event',
      'Brand refresh, top to bottom',
      'Booking page for a salon',
    ],
  },
  bookkeeping: {
    queries: [
      'bookkeeper working accounts desk',
      'accounting paperwork calculator',
      'financial records spreadsheet desk',
      'small business accounting invoices',
      'accountant reviewing documents',
      'receipts invoices organised desk',
    ],
    captions: [
      'Books brought current, 12 months',
      'GCT filing prepared for TAJ',
      'Invoicing system set up',
      'Payroll run monthly',
      'Expenses tracked and categorised',
      'Year-end pack for the accountant',
    ],
  },
  'social-media': {
    queries: [
      'social media manager phone content',
      'content creation phone photography',
      'social media marketing workspace',
      'instagram content planning desk',
      'phone filming product content',
      'social media analytics screen',
    ],
    captions: [
      'Content calendar, one month ahead',
      'Product shoot for Instagram',
      'Reels that tripled reach',
      'Page rebuilt with a proper bio',
      'Paid promotion set up',
      'Weekly posting, hands off',
    ],
  },
  delivery: {
    queries: [
      'delivery rider motorcycle package',
      'courier delivering package door',
      'delivery driver with parcels',
      'food delivery bag scooter',
      'courier van package delivery',
      'delivery rider city street',
    ],
    captions: [
      'Same-day across the corporate area',
      'Documents delivered before noon',
      'Food runs, lunch rush',
      'Fragile items, handled careful',
      'Daily route for a small shop',
      'Airport pickup and drop',
    ],
  },
  moving: {
    queries: [
      'movers carrying furniture truck',
      'moving boxes house removal',
      'removal truck loading furniture',
      'movers loading van boxes',
      'house moving day boxes',
      'furniture delivery two men',
    ],
    captions: [
      'Three-bedroom move in one day',
      'Office relocated over a weekend',
      'Furniture delivered and assembled',
      'Dump run, yard cleared',
      'Piano moved, no scratches',
      'Truck and two helpers included',
    ],
  },
  'car-detailing': {
    queries: [
      'car detailing polishing exterior',
      'car interior cleaning detailing',
      'car wash foam cleaning',
      'auto detailing buffing paint',
      'clean car interior detailed',
      'car detailing tools products',
    ],
    captions: [
      'Full detail, inside and out',
      'Paint corrected and waxed',
      'Seats shampooed and dried',
      'Engine bay cleaned',
      'Headlights restored, clear again',
      'Mobile service, done at your gate',
    ],
  },
  'generator-repair': {
    queries: [
      'generator repair mechanic engine',
      'small engine repair workshop',
      'portable generator maintenance',
      'lawnmower engine repair tools',
      'engine carburettor repair hands',
      'generator servicing technician',
    ],
    captions: [
      'Generator serviced, starts first pull',
      'Carburettor stripped and cleaned',
      'Starter motor replaced',
      'Lawnmower back in service',
      'Pressure washer pump rebuilt',
      'Standby unit load-tested',
    ],
  },
  security: {
    queries: [
      'security guard uniform building',
      'security officer event crowd',
      'security guard gate entrance',
      'night security patrol building',
      'security personnel construction site',
      'security guard standing post',
    ],
    captions: [
      'Night cover for a construction site',
      'Event security, 400 guests',
      'Gate duty, residential complex',
      'Two officers, weekend shifts',
      'Business premises, after hours',
      'Escort for a cash run',
    ],
  },
};

/**
 * Portrait searches for demo avatars.
 *
 * Weighted towards Black and Caribbean subjects on purpose: a Jamaican
 * marketplace whose every face is a Northern European stock model undercuts
 * the pitch before a judge has read a single line of the deck. Stock libraries
 * still skew, so the queries push explicitly rather than hoping.
 */
export const AVATAR_QUERIES = [
  'black man portrait smiling',
  'black woman portrait smiling',
  'caribbean man portrait',
  'caribbean woman portrait',
  'african american man headshot',
  'african american woman headshot',
  'black man professional headshot',
  'black woman professional headshot',
  'black tradesman portrait',
  'black woman entrepreneur portrait',
  'older black man portrait',
  'older black woman portrait',
  'young black man portrait outdoors',
  'young black woman portrait outdoors',
  'black business owner portrait',
  'smiling worker portrait uniform',
];

/** Fallback for any trade slug not covered above. */
export const GENERIC_IMAGERY = {
  queries: [
    'small business owner working',
    'skilled tradesperson at work',
    'artisan working workshop',
    'service professional working',
  ],
  captions: [
    'Job completed for a repeat customer',
    'Finished and signed off',
    'Another one done this month',
    'Booked through myB',
  ],
};
